# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Python编程技巧')),
                ('desc', models.CharField(max_length=100, verbose_name='Web框架使用')),
                ('manager_name', models.CharField(max_length=100, verbose_name='HTML页面技术')),
            ],
        ),
    ]
