# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '首页', 'verbose_name_plural': '首页板块'},
        ),
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '删除')], default=0, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='板块描述'),
        ),
        migrations.AlterField(
            model_name='block',
            name='manager_name',
            field=models.CharField(max_length=100, verbose_name='管理员名字'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=100, verbose_name='板块标题'),
        ),
    ]
