# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_to_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论内容', 'verbose_name_plural': '评论内容'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment', verbose_name='被回复评论ID'),
        ),
    ]
